spring:
  application:
    name: VolunteerHubBackend
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      google:
        https://accounts.google.com
      volunteerhub:
        http://localhost:7070

server:
  port: ${PORT}

